name: Github Action 연습하기
on: push

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: 첫 번째 작업
        run: echo "첫 번째 작업 실행 중"

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "이건 첫 번째 레슨"
          echo "좋은 건 너만 알기 ~~~"
